# VocalInsight AI プロジェクト向けワークフロー設定

name: 'GitHub Copilot Review'
on:
  pull_request:
    types: [opened, synchronize, reopened]

# Copilot PR Reviewerの設定
env:
  # レビュー言語設定
  COPILOT_REVIEW_LANGUAGE: 'ja'
  # プロジェクト固有設定
  PROJECT_NAME: 'VocalInsight AI'
  PRIMARY_LANGUAGE: 'Python'
  
# このファイルは将来的なGitHub Actions統合の準備として作成
# 現在はcopilot-instructions.mdが主要な設定ファイル